import Head from "next/head";
import styles from "../styles/home.module.scss";
import Image from "next/image";
import techsImage from "../../public/images/techs.svg";

import { Inter } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>Mudando de vida </title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>
      <main className={styles.container}>
        <div className={styles.containerHeader}>
          <section className={styles.ctaText}>
            <h1>Levando você ao próximo nível</h1>
            <span>
              Lorem ipsum dolor sit, amet consectetur adipisicing elit. Labore
              voluptas magnam, reiciendis earum voluptates, eius deserunt ullam
              accusantium nisi inventore aliquid officia expedita! Libero sed
              nostrum animi hic debitis doloremque.
            </span>
            <a>
              <button>Começar Agora</button>
            </a>
          </section>
          <img src="/images/banner-conteudos.png" alt="Conteúdo" />
        </div>
        <hr className={styles.divisor} />

        <div className={styles.sectionContent}>
          <section>
            <h2>Aprenda a estudar</h2>
            <span>
              Lorem, ipsum dolor sit amet consectetur adipisicing elit.
              Perspiciatis mollitia laborum soluta ipsum quod neque ratione
              aspernatur
            </span>
          </section>
          <img src="/images/financasApp.png" alt="Conteúdo de finanças" />
        </div>

        <hr className={styles.divisor} />

        <div className={styles.sectionContent}>
          <img src="/images/webDev.png" alt="Conteúdo de aplicações" />
          <section>
            <h2>Aprenda a estudar mais ainda</h2>

            <span>
              Lorem, ipsum dolor sit amet consectetur adipisicing elit.
              Perspiciatis mollitia laborum soluta ipsum quod neque ratione
              aspernatur
            </span>
          </section>
        </div>

        <div className={styles.nextLevelContent}>
          <Image quality={100} src={techsImage} alt="Tecnologia" />

          <h2>
            Mais de <span className={styles.alunos}>15 mil</span> já levaram sua
            carreira ao next level
          </h2>
          <span>
            E você vai perder a chance de evoluir de uma vez por todas?
          </span>
          <a>
            <button>Acessar turma!</button>
          </a>
        </div>
      </main>
    </>
  );
}
